# Generated by Django 4.1.2 on 2022-11-18 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Title')),
                ('logo', models.ImageField(upload_to='uploads/%Y/%m/%d', verbose_name='Photo')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price, BYN')),
                ('book_year', models.PositiveIntegerField(verbose_name='Year of publishing')),
                ('book_pages', models.IntegerField(verbose_name='Number of pages')),
                ('book_format', models.CharField(max_length=100, verbose_name='Format')),
                ('book_isbn', models.CharField(max_length=100, verbose_name='ISBN')),
                ('book_mass', models.IntegerField(verbose_name='Mass')),
                ('books_in_stock', models.IntegerField(verbose_name='Books in Stock')),
                ('book_status', models.BooleanField(verbose_name='Status')),
                ('book_rating', models.IntegerField(verbose_name='Rating')),
                ('book_input_in_catalog', models.DateField(auto_now_add=True, verbose_name='Date of entry into catalogue')),
                ('book_last_change', models.DateField(auto_now=True, verbose_name='Last changes date')),
                ('book_age_limits', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referencies.agelimit', verbose_name='Age limits')),
                ('book_author', models.ManyToManyField(blank=True, related_name='book_authors', to='referencies.author', verbose_name='Authors')),
                ('book_cover', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referencies.cover', verbose_name='Cover')),
                ('book_genrie', models.ManyToManyField(blank=True, related_name='book_genriess', to='referencies.genrie', verbose_name='Genrie')),
                ('book_ph', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referencies.publishinghouse', verbose_name='Publishing House')),
                ('book_serie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referencies.serie', verbose_name='Serie')),
            ],
        ),
    ]
