# Generated by Django 4.1.2 on 2022-10-26 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referencies', '0004_agelimit_cover_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название книги')),
                ('logo', models.ImageField(upload_to='uploads/%Y/%m/%d', verbose_name='Фото обложки')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена, BYN')),
                ('book_year', models.DateField(verbose_name='Год издания')),
                ('book_pages', models.IntegerField(verbose_name='Страницы')),
                ('book_format', models.CharField(max_length=100, verbose_name='Формат')),
                ('book_isbn', models.CharField(max_length=100, verbose_name='ISBN')),
                ('book_mass', models.IntegerField(verbose_name='Вес')),
                ('books_in_stock', models.IntegerField(verbose_name='Вес')),
                ('book_status', models.BooleanField(verbose_name='Статус')),
                ('book_rating', models.IntegerField(verbose_name='Рейтинг')),
                ('book_input_in_catalog', models.DateField()),
                ('book_last_change', models.DateField()),
                ('book_age_limits', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referencies.agelimit', verbose_name='Возрастные ограничения')),
                ('book_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referencies.author', verbose_name='Авторы')),
                ('book_cover', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referencies.cover', verbose_name='Переплет')),
                ('book_genrie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referencies.genrie', verbose_name='Жанры')),
                ('book_ph', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referencies.publishinghouse', verbose_name='Издательство')),
                ('book_serie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referencies.serie', verbose_name='Серия')),
            ],
        ),
    ]
