# Generated by Django 4.1.2 on 2022-10-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencies', '0004_agelimit_cover_rate'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_author',
        ),
        migrations.AddField(
            model_name='book',
            name='book_author',
            field=models.ManyToManyField(blank=True, related_name='book_authors', to='referencies.author', verbose_name='Авторы'),
        ),
    ]
