# Generated by Django 4.1.2 on 2022-12-08 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_comment', to='books.book', verbose_name='Book to comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_comment', to=settings.AUTH_USER_MODEL, verbose_name='Comment of the user')),
            ],
        ),
    ]
