# Generated by Django 4.1.2 on 2022-11-21 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referencies', '0001_initial'),
        ('books', '0002_remove_book_book_author_book_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_genrie',
        ),
        migrations.AddField(
            model_name='book',
            name='book_genrie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='referencies.genrie', verbose_name='Genrie'),
        ),
    ]
