# Generated by Django 4.1.2 on 2022-10-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencies', '0004_agelimit_cover_rate'),
        ('books', '0002_remove_book_book_author_book_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_genrie',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_input_in_catalog',
            field=models.DateField(verbose_name='Дата внесения в каталог'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_last_change',
            field=models.DateField(verbose_name='Дата последнего изменения'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_genrie',
            field=models.ManyToManyField(blank=True, related_name='book_genriess', to='referencies.genrie', verbose_name='Жанры'),
        ),
    ]
