# Generated by Django 4.1.2 on 2022-11-30 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referencies', '0002_status'),
        ('books', '0003_remove_book_book_genrie_book_book_genrie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='referencies.author', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_genrie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='referencies.genrie', verbose_name='Genrie'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_ph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='referencies.publishinghouse', verbose_name='Publishing House'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='referencies.serie', verbose_name='Serie'),
        ),
    ]
