# Generated by Django 4.1.2 on 2022-11-13 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referencies', '0005_alter_agelimit_description_alter_agelimit_name_and_more'),
        ('books', '0003_remove_book_book_genrie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_age_limits',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referencies.agelimit', verbose_name='Age limits'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_author',
            field=models.ManyToManyField(blank=True, related_name='book_authors', to='referencies.author', verbose_name='Authors'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referencies.cover', verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_format',
            field=models.CharField(max_length=100, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_genrie',
            field=models.ManyToManyField(blank=True, related_name='book_genriess', to='referencies.genrie', verbose_name='Genrie'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_input_in_catalog',
            field=models.DateField(auto_now_add=True, verbose_name='Date of entry into catalogue'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_last_change',
            field=models.DateField(auto_now=True, verbose_name='Last changes date'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_mass',
            field=models.IntegerField(verbose_name='Mass'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_pages',
            field=models.IntegerField(verbose_name='Number of pages'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_ph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referencies.publishinghouse', verbose_name='Publishing House'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_rating',
            field=models.IntegerField(verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referencies.serie', verbose_name='Serie'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_status',
            field=models.BooleanField(verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_year',
            field=models.DateField(verbose_name='Year of publishing'),
        ),
        migrations.AlterField(
            model_name='book',
            name='books_in_stock',
            field=models.IntegerField(verbose_name='Books in Stock'),
        ),
        migrations.AlterField(
            model_name='book',
            name='logo',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price, BYN'),
        ),
    ]
