# Generated by Django 4.1.2 on 2022-11-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_book_age_limits_alter_book_book_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_year',
            field=models.PositiveIntegerField(verbose_name='Year of publishing'),
        ),
    ]
