# Generated by Django 4.1.2 on 2022-10-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencies', '0002_genrie_publishinghouse_serie_units_alter_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Имя автора'),
        ),
        migrations.AlterField(
            model_name='genrie',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='genrie',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='publishinghouse',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='publishinghouse',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Издательство'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='units',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='units',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Единицы измерения'),
        ),
    ]
