# Generated by Django 4.1.2 on 2022-12-10 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_ordercomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercomment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_comment', to='orders.order', verbose_name='Order to comment'),
        ),
        migrations.AlterField(
            model_name='ordercomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_comment', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
