# Generated by Django 4.1.2 on 2022-11-22 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_bookincart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookincart',
            old_name='prise',
            new_name='price',
        ),
    ]
