# Generated by Django 4.1.2 on 2022-11-22 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_book_genrie_book_book_genrie'),
        ('orders', '0003_rename_prise_bookincart_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookincart',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_price', to='books.book', verbose_name='Price'),
        ),
    ]
