# Generated by Django 4.1.2 on 2022-11-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Information'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(default='add', verbose_name='Delivery Address'),
            preserve_default=False,
        ),
    ]
