# Generated by Django 4.1.2 on 2022-11-30 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_additional_info_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookincart',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_in_cart', to='orders.cart', verbose_name='Cart'),
        ),
    ]
