# Generated by Django 4.1.2 on 2022-12-05 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_bookincart_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookincart',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='orders.cart', verbose_name='Cart'),
        ),
    ]
