# Generated by Django 4.1.2 on 2022-12-07 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last name')),
                ('phone', models.PositiveIntegerField(verbose_name='Phone number')),
                ('home_country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Home country')),
                ('home_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Home city')),
                ('home_index', models.CharField(blank=True, max_length=100, null=True, verbose_name='Home index')),
                ('home_address1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Home address1')),
                ('home_address2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Home address2')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Additional info')),
                ('group', models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name='Group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
    ]
