# Generated by Django 4.1.2 on 2022-11-18 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.PositiveIntegerField(verbose_name='Phone number')),
                ('home_country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Home country')),
                ('home_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Home city')),
                ('home_index', models.CharField(blank=True, max_length=100, null=True, verbose_name='Home index')),
                ('home_address1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Home address1')),
                ('home_address2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Home address2')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Additional info')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
