# Generated by Django 4.1.2 on 2022-11-16 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Name of the Group')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='User email')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='User name')),
                ('surname', models.CharField(blank=True, max_length=150, null=True, verbose_name='User surname')),
                ('phone', models.PositiveIntegerField(verbose_name='User phone')),
                ('home_country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('home_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('home_index', models.CharField(blank=True, max_length=100, null=True, verbose_name='Index')),
                ('home_address1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address 1')),
                ('home_address2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address 2')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Additional information')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homepage.usersgroup', verbose_name='User group')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
        ),
    ]
