# Generated by Django 4.1.2 on 2022-11-29 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('homepage', '0006_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name='Group'),
        ),
    ]
