# Generated by Django 4.1.2 on 2022-11-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_alter_profile_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.PositiveIntegerField(default='111111111', verbose_name='Phone number'),
        ),
    ]
